version: '3'

services:
  web:
    build: .
    ports:
      - ${APP_PORT}:3000
    environment:
      - WEATHER_API_KEY=${APP_WEATHER_API_KEY}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
